# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
 name: demo

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Instalar Node.js'

- script: |
   npm install
   npm run build
  displayName: 'Instalar dependencias y construir'

- script: |
   npm test
  displayName: 'Ejecutar pruebas'